routes/web.php
<?php

Auth::routes();

Route::match(['get', 'post'], 'register', function () {
    return redirect()->back();
});


// SWITCH LANGUAGE
Route::name('locale.switch')->get('lang/{locale}', 'LocaleController@switch');

// HOME
Route::get('/', 'HomeController@index')->name('site');

// FAQ
Route::get('/faq', 'FaqsController@index')->name('faq');
Route::get('/faq/{slug}', 'FaqsController@category')->name('faq.category');

// NEWSLETTER
Route::post('newsletter', 'SubscribersController@subscribe')->name('newsletter.subscribe');

// WHITE PAPER DOWNLOAD
Route::post('download', 'DownloadsController@download')->name('downloads.downloadPDF');
Route::get('downloads/{token}', 'DownloadsController@downloadPDF')->name('downloads.id-token');

// CONTACT
Route::post('contact', 'ContactMailController@sendMail')->name('contact.send');


// PAINEL ROUTES
Route::group(['middleware' => ['auth'], 'prefix' => 'painel', 'namespace' => 'Painel'], function () {
    // LOGS
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    // DASHBOARD
    Route::get('dashboard', 'DashboardController@index')->name('dashboard');

    // NEWSLETTER
    Route::get('newsletter/subscribers', 'SubscribersController@subscribers')->name('newsletters.subscribers');

    // BANNERS
    Route::resource('banners', 'BannersController');

    // FAQS
    Route::get('faq/trashed', 'FaqsController@trashed')->name('faq.trashed');
    Route::post('faq/{id}/restore', 'FaqsController@restore')->name('faq.restore');
    Route::post('faq/{id}/forceDelete', 'FaqsController@forceDelete')->name('faq.forceDelete');
    Route::resource('faq', 'FaqsController');

    // CATEGORY FAQS
    Route::resource('category-faq', 'CategoryFaqController');

    // PAGES
    Route::get('pages/trashed', 'PagesController@trashed')->name('pages.trashed');
    Route::post('pages/{id}/restore', 'PagesController@restore')->name('pages.restore');
    Route::post('pages/{id}/forceDelete', 'PagesController@forceDelete')->name('pages.forceDelete');
    Route::resource('pages', 'PagesController');

    // TEAMS
    Route::get('teams/trashed', 'TeamsController@trashed')->name('teams.trashed');
    Route::post('teams/{id}/restore', 'TeamsController@restore')->name('teams.restore');
    Route::post('teams/{id}/forceDelete', 'TeamsController@forceDelete')->name('teams.forceDelete');
    Route::resource('teams', 'TeamsController');

    // REASONS
    Route::get('reasons/trashed', 'ReasonsController@trashed')->name('reasons.trashed');
    Route::post('reasons/{id}/restore', 'ReasonsController@restore')->name('reasons.restore');
    Route::post('reasons/{id}/forceDelete', 'ReasonsController@forceDelete')->name('reasons.forceDelete');
    Route::resource('reasons', 'ReasonsController');

    // WORKS
    Route::get('works/trashed', 'WorksController@trashed')->name('works.trashed');
    Route::post('works/{id}/restore', 'WorksController@restore')->name('works.restore');
    Route::post('works/{id}/forceDelete', 'WorksController@forceDelete')->name('works.forceDelete');
    Route::resource('works', 'WorksController');

    // DOWLOADS
    Route::get('downloads/{id}/downloadFile', 'DownloadsController@downloadFile')->name('downloads.downloadFile');
    Route::get('downloads/trashed', 'DownloadsController@trashed')->name('downloads.trashed');
    Route::post('downloads/{id}/restore', 'DownloadsController@restore')->name('downloads.restore');
    Route::post('downloads/{id}/forceDelete', 'DownloadsController@forceDelete')->name('downloads.forceDelete');
    Route::resource('downloads', 'DownloadsController');

    // USERS
    Route::get('users/trashed', 'UserController@trashed')->name('users.trashed');
    Route::post('users/{id}/restore', 'UserController@restore')->name('users.restore');
    Route::post('users/{id}/forceDelete', 'UserController@forceDelete')->name('users.forceDelete');
    Route::resource('users', 'UserController');

    // PROFILE
    Route::get('meu-perfil', 'ProfileController@profile')->name('painel.profile');
    Route::post('atualizar-perfil', 'ProfileController@profileUpdate')->name('painel.profile.update');
    Route::get('alterar-senha', 'ProfileController@password')->name('painel.profile.password');
    Route::post('atualizar-senha', 'ProfileController@passwordUpdate')->name('painel.profile.password.update');
});

app/Http/Controllers/Painel/BannersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Models\Banner;
use App\Http\Requests\BannerStoreRequest;
use App\Http\Requests\BannerUpdateRequest;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Intervention\Image\Facades\Image;

class BannersController extends Controller
{
    protected $banner;

    /**
     * BannersController constructor.
     * @param Banner $banner
     */
    public function __construct(Banner $banner)
    {
        $this->banner = $banner;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banners = $this->banner::orderBy('title', 'ASC')->paginate(10);

        return view('painel.banners.index', compact('banners'))->with('titlePage', 'Banners');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $banner = $this->banner;
        return view('painel.banners.create', compact('banner'))->with('titlePage', trans('painel.models.crud.create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param BannerStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(BannerStoreRequest $request)
    {
        $data = $request->all();
        $filename = '';
        if ($request->hasFile('image'))
        {
            $file       = $request->file('image', null);
            $filename   = sha1($file->getClientOriginalName() . microtime()) . '.' . $file->getClientOriginalExtension();
            $img        = Image::make($file);

            $img->save(public_path() . '/img/uploads/banners/' . "banner-" . $filename);
        }
        $data['image'] = "banner-" . $filename;

        $create = $this->banner::create($data);

        if ($create) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.create'));
            return redirect()->route('banners.edit', $create->id);
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.create'));
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $banner = $this->banner::withTrashed()->findOrFail($id);
        return view('painel.banners.show', compact('banner'))
            ->with('titlePage', $banner->title);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $status = $this->banner::statusList();
        $banner = $this->banner::withTrashed()->findOrFail($id);
        return view('painel.banners.edit', compact('banner', 'status'))
            ->with('titlePage', trans('painel.models.crud.edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param BannerUpdateRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(BannerUpdateRequest $request, $id)
    {
        $banner = $this->banner::withTrashed()->findOrFail($id);
        $data = $request->all();
        $data['user_id'] = auth()->user()->getAuthIdentifier();

        if ($request->hasFile('image'))
        {
            if ($banner->image) {
                $imageUrl = public_path() . '/img/uploads/banners/' . $banner->image;
                $banner->image = '';
                $banner->update();
                File::delete($imageUrl);
            }
            $file       = $request->file('image', null);
            $filename   = sha1($file->getClientOriginalName() . microtime()) . '.' . $file->getClientOriginalExtension();
            $img        = Image::make($file);

            $img->save(public_path() . '/img/uploads/banners/' . "banner-" . $filename);
            $data['image'] = "banner-" . $filename;
        }

        $banner = $this->banner::withTrashed()->findOrFail($id)->update($data);

        if ($banner) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.edit'));
            return redirect()->route('banners.index');
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.edit'));
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $banner = $this->banner::findOrFail($id);

        $delete = $banner->delete();

        if ($delete) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.create'));
            return redirect()->route('banners.index');
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.create'));
        return redirect()->back();
    }

    /**
     * Restore
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function restore($id)
    {
        $banner = $this->banner::withTrashed()->where('id', $id)->first();

        DB::beginTransaction();

        $restore = $banner->restore();

        if ($restore && $banner->deleted_at == null) {
            DB::commit();
            $banner['status'] = 1;
            $banner->update();
            session()->flash('success', trans('painel.controllers.flash-messages.success.create'));
            return redirect()->route('banners.index');
        }
        DB::rollback();
        session()->flash('danger', trans('painel.controllers.flash-messages.error.create'));
        return redirect()->back();
    }

    /**
     * @return $this
     */
    public function trashed()
    {
        $banners = $this->banner::onlyTrashed()->paginate();

        return view('painel.banners.trashed',
            compact('banners'))->with('titlePage', trans('painel.models.crud.trasheds'));
    }
}

app/Http/Controllers/Painel/CategoryFaqController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Models\Faq;
use App\Models\CategoryFaq;
use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryFaqStoreRequest;
use App\Http\Requests\CategoryFaqUpdateRequest;
use Illuminate\Http\Request;

class CategoryFaqController extends Controller
{
    protected $faq;
    protected $categoryFaq;

    /**
     * CategoryFaqController constructor.
     * @param $faq
     * @param $categoryFaq
     */
    public function __construct(Faq $faq, CategoryFaq $categoryFaq)
    {
        $this->faq = $faq;
        $this->categoryFaq = $categoryFaq;
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = $this->categoryFaq->paginate(15);

        return view('painel.category-faq.index', compact('categories'))->with('titlePage', trans('painel.models.crud.index'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @param CategoryFaq $category
     * @return \Illuminate\Http\Response
     */
    public function create(CategoryFaq $category)
    {
        return view('painel.category-faq.create', compact('category'))->with('titlePage', trans('painel.models.crud.create'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CategoryFaqStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryFaqStoreRequest $request)
    {
        $data = $request->all();
        $data['slug'] = str_slug($data['name'], '-');

        $create = $this->categoryFaq->create($data);

        if ($create) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.create'));
            return redirect()->route('category-faq.edit', $create->id);
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.create'));
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $category = $this->categoryFaq::findOrFail($id);

        return view('painel.category-faq.show', compact('category'))->with('titlePage', $category->name);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryFaq::findOrFail($id);
        return view('painel.category-faq.edit', compact('category'))->with('titlePage', trans('painel.models.crud.edit'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param CategoryFaqUpdateRequest $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryFaqUpdateRequest $request, $id)
    {
        $category = $this->categoryFaq::findOrFail($id);
        $data = $request->all();
        $update = $category->update($data);

        if ($update) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.edit'));
            return redirect()->route('category-faq.index');
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.edit'));
        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $delete = $this->categoryFaq::findOrFail($id)->delete();

        if ($delete) {
            session()->flash('success', trans('painel.controllers.flash-messages.success.create'));
            return redirect()->route('category-faq.index');
        }
        session()->flash('danger', trans('painel.controllers.flash-messages.error.create'));
        return redirect()->back();
    }
}

app/Http/Controllers/Painel/DashboardController.php
<?php

namespace App\Http\Controllers\Painel;

use Carbon\Carbon;
use Illuminate\Support\Facades\DB;
use Spatie\Analytics\Period;
use Spatie\Analytics\Analytics;
use App\Models\Subscriber;
use App\Models\SubscriberDownload;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    public $subscriber;
    public $download;

    /**
     * DashboardController constructor.
     * @param Subscriber $subscriber
     * @param SubscriberDownload $download
     */
    public function __construct(Subscriber $subscriber, SubscriberDownload $download)
    {
        $this->subscriber = $subscriber;
        $this->download = $download;
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $series = ['20,10'];
        $subscribers = $this->subscriber::where('status', 1)->get();
        $newSubscribers = $this->subscriber->select(DB::raw('count(id) as `total_subscribers`'), DB::raw("MONTH(created_at) as week"))
            ->groupby('week')
            ->where('status', 1)
            ->get();

        $canceledSubscribers = $this->subscriber::where('status', 2)->get();

        $query = DB::raw(
            "select count(download_id) as total_download, MONTH(created_at) as mes from subscriber_download group by mes"
        );
        $downloadSelect = DB::select($query);
        $downloads = json_decode(json_encode($downloadSelect),true);

        $totalDownloads = $this->download::all();

        $accessors = \Analytics::fetchTotalVisitorsAndPageViews(Period::days(7));

        $countAccessors = $accessors->sum('visitors');
        $countPageViews = $accessors->sum('pageViews');

        return view('painel.dashboard', compact('series', 'subscribers','newSubscribers', 'canceledSubscribers', 'downloads', 'totalDownloads', 'accessors', 'countAccessors', 'countPageViews'))->with('titlePage', 'Dashboard');
    }
}

app/Http/Controllers/Painel/SubscribersController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Models\Download;
use App\Models\Subscriber;
use App\Http\Controllers\Controller;

class SubscribersController extends Controller
{
    protected $subscriber;
    protected $download;

    public function __construct (Subscriber $subscriber, Download $download)
    {
        $this->subscriber = $subscriber;
        $this->download = $download;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function subscribers()
    {
        $subscribers = $this->subscriber::orderBy('created_at')->paginate(20);

        $subscribeCount = $subscribers->count();

        return view('painel.newsletters.subscribers', compact('subscribers', 'subscribeCount'))->with('titlePage', 'inscritos via Newsletter');
    }
}

resources/views/_partials/painel/sidebar.blade.php
<div class="sidebar" data-color="default">
    <div class="logo">
        <a href="{{ route('dashboard') }}" class="logo-text">
            {{ config('app.name') }}
            <img src="{{ asset('img/' . app()->getLocale()) . '.jpeg' }}" alt="{{ app()->getLocale() }}" style="margin-left: 5px;">
        </a>
    </div>

    <div class="sidebar-wrapper">
        <div class="user">
            <a href="{{ route('painel.profile') }}">
                <div class="photo">
                    <img src="{{ asset('painel/img/default-avatar.png') }}" />
                </div>
                <div class="info">
                    <div class="text-center">
                        @if (auth()->check())
                            {{ auth()->user()->name }} <br>
                            <small>@lang('painel.titles.my-profile')</small>
                        @endif
                    </div>
                </div>
            </a>
        </div>

        <ul class="nav">
            <li>
                <a href="{{ route('dashboard') }}">
                    <i class="pe-7s-graph"></i>
                    <p>Painel</p>
                </a>
            </li>

            {{--BANNERS--}}
            <li>
                <a data-toggle="collapse" href="#banenrs">
                    <i class="pe-7s-albums"></i>
                    <p>
                        @lang('painel.menu.banners')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="banenrs">
                    <ul class="nav">
                        <li><a href="{{ route('banners.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('banners.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            {{--PAGES--}}
            <li>
                <a data-toggle="collapse" href="#pages">
                    <i class="pe-7s-folder"></i>
                    <p>
                        @lang('painel.menu.pages')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="pages">
                    <ul class="nav">
                        <li><a href="{{ route('pages.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('pages.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            {{--WORKS--}}
            <li>
                <a data-toggle="collapse" href="#works">
                    <i class="pe-7s-config"></i>
                    <p>
                        @lang('painel.menu.how_works')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="works">
                    <ul class="nav">
                        <li><a href="{{ route('works.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('works.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            {{--REASONS--}}
            <li>
                <a data-toggle="collapse" href="#reasons">
                    <i class="pe-7s-menu"></i>
                    <p>
                        @lang('painel.menu.reasons')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="reasons">
                    <ul class="nav">
                        <li><a href="{{ route('reasons.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('reasons.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            {{--TEAMS--}}
            <li>
                <a data-toggle="collapse" href="#teams">
                    <i class="pe-7s-wallet"></i>
                    <p>
                        @lang('painel.menu.teams')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="teams">
                    <ul class="nav">
                        <li><a href="{{ route('teams.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('teams.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            {{--WHITE PAPER--}}
            <li>
                <a href="{{ route('downloads.index') }}">
                    <i class="pe-7s-cloud-download"></i>
                    <p>@lang('painel.menu.downloads')</p>
                </a>
            </li>

            {{--FAQS--}}
            <li>
                <a data-toggle="collapse" href="#faq">
                    <i class="pe-7s-wallet"></i>
                    <p>
                        @lang('painel.menu.faqs')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="faq">
                    <ul class="nav">
                        <li><a href="{{ route('faq.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('faq.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                        <li><a href="{{ route('category-faq.index') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.faq-category')</a></li>
                    </ul>
                </div>
            </li>

            {{-- NEWSLTTER--}}
            <li>
                <a href="{{ route('newsletters.subscribers') }}">
                    <i class="fa fa-envelope-o"></i>
                    <p>@lang('painel.menu.newsletters')</p>
                </a>
            </li>

            {{--USERS--}}
            <li>
                <a data-toggle="collapse" href="#users">
                    <i class="pe-7s-users"></i>
                    <p>
                        @lang('painel.menu.users')
                        <b class="caret"></b>
                    </p>
                </a>
                <div class="collapse" id="users">
                    <ul class="nav">
                        <li><a href="{{ route('users.index') }}"><i class="fa fa-bars" aria-hidden="true"></i> @lang('painel.menu.list')</a></li>
                        <li><a href="{{ route('users.create') }}"><i class="fa fa-plus" aria-hidden="true"></i> @lang('painel.menu.create')</a></li>
                    </ul>
                </div>
            </li>

            <hr class="user-profile-menu">

            <li class="hidden-lg hidden-md hidden-sm">
                <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('form-logout').submit();">
                    <i class="fa fa-sign-out"></i> @lang('painel.titles.logout')
                </a>
                <form id="form-logout" action="{{ route('logout') }}" method="POST" style="display: none;">
                    {{ csrf_field() }}
                </form>
            </li>
        </ul>
    </div>{{--sidebar-wrapper--}}
</div>{{--sidebar--}}

resources/views/_partials/painel/top-navbar.blade.php
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-minimize">
            <button id="minimizeSidebar" class="btn btn-default btn-fill btn-sm">
                <i class="fa fa-ellipsis-v visible-on-sidebar-regular"></i>
                <i class="fa fa-navicon visible-on-sidebar-mini"></i>
            </button>
        </div>
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ route('dashboard') }}">{{ config('app.name') }}</a>
        </div>
        <h3 class="title-page"> - {{ $titlePage }} </h3>


        <div class="pull-right" id="btnLogout">
            @foreach (config('app.locales') as $localeKey => $locale)
                @if ($localeKey !== app()->getLocale())
                    <a href="{{ route('locale.switch', $localeKey) }}" class="small text-muted">
                        @lang('painel.titles.change-lang') {{ $locale }}
                        <img src="{{ asset('img/' . $localeKey) . '.jpeg' }}" alt="{{ app()->getLocale() }}" style="margin-right: 25px;">
                    </a>
                @endif
            @endforeach

            <a href="{{ config('app.url')}}" class="btn btn-info btn-fill btn-xs hidden-xs" target="_blank">
                <i class="fa fa-home"></i> @lang('painel.titles.go-to-site')
            </a>

            <a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();" class="btn btn-default btn-fill btn-xs hidden-xs">
                <i class="fa fa-sign-out"></i> @lang('painel.titles.logout')
            </a>
            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                {{ csrf_field() }}
            </form>
        </div>
    </div>
</nav>